### ISSUE TITLE
kCLAuthorizationStatusAuthorized deprecated in 8.0 SDK

### ISSUE THREAD

**Issue by bravobug** [clusterinc/ClusterPrePermissions#14]
`locationAuthorizationStatusPermitsAccess:` is referencing a deprecated constant (`kCLAuthorizationStatusAuthorized`) which causes a compiler warning. Would be nice if this could be fixed (with a check for `__IPHONE_8_0` etc.).

**Comment by confile** [comment]
@bravobug  Could you please post the code line you think should be changed?

**Comment by rsattar** [comment]
There are no references to `kCLAuthorizationStatusAuthorized` anymore, last I checked, so closing this :)
