### ISSUE TITLE
push notification permissions

### ISSUE THREAD

**Issue by hsavit1** [clusterinc/ClusterPrePermissions#19]
plan on adding this any time soon?

**Comment by rsattar** [comment]
Waiting for https://github.com/clusterinc/ClusterPrePermissions/pull/16 to be separated into different requests. Feel free to nudge them!

**Comment by hsavit1** [comment]
for sure.

**Comment by s5** [comment]
I think it's safe to say at this point that it's never going to be separated into different requests. :) Anyone else up to the task?

**Comment by confile** [comment]
+1

**Comment by chetem** [comment]
+1

**Comment by confile** [comment]
https://github.com/clusterinc/ClusterPrePermissions/pull/23

**Comment by chetem** [comment]
:+1: cheers!

**Comment by danipralea** [comment]
I still cannot see push notifications permissions. Am I looking in the wrong place or is it coming?

**Comment by rsattar** [comment]
Hey folks, I'm merging in @confile's push notification pre-permission, but I have some issues with the change. See here: https://github.com/clusterinc/ClusterPrePermissions/pull/23#issuecomment-141512023

The bottom line is that push notifications permissions don't work the same way as other permissions, and it requires a lot more integration into the app delegate. Supporting it in ClusterPrePermissions is never going to be fully reliable (See [my pull request comment](https://github.com/clusterinc/ClusterPrePermissions/pull/23#issuecomment-141512023)).
