### ISSUE TITLE
Microphone permission not working

### ISSUE THREAD

**Issue by kwade101** [clusterinc/ClusterPrePermissions#20]
It appears that the microphone permission is not working. To reproduce this, I simply modified the PermissionsTestViewController.m file and changed the  [permissions showPhotoPermissionsWithTitle...] call to  [permissions showMicrophonePermissionsWithTitle...]

No other changes.  Now, the UIAlert fires. But no matter which option I select -- 'Not Now' or 'Give Access' -- user action is always denied and system action is always 'no action taken'.  And hasPermission is, therefore, always NO.

Any ideas?

**Comment by rsattar** [comment]
Thanks @kwade101.

I've been super busy lately, but I'll take a look soon.

**Comment by azimin** [comment]
@rsattar 
Problem is inside `ClusterPrePermissions.m` at line 218, you use `AVMediaTypeVideo` for microphone, but it's `AVMediaTypeAudio` type :)

**Comment by rsattar** [comment]
Thanks everyone. Pushed 0.6.0 that has a fix for this. Sorry for the delay.
