### ISSUE TITLE
Motion Activity

### ISSUE THREAD

**Issue by mythodeia** [clusterinc/ClusterPrePermissions#7]
Hello and thanks for this excellent library.
can you expand this lib to support motion activity pre-permissions?

thanks

**Comment by rsattar** [comment]
Hello @mythodeia. Unfortunately in iOS there is no way to check the authorization status of Motion Activity, so there is no way to ask for pre-permissions for it. Even in Apple's own sample app, Privacy Prompts, they do not show how to check the status, only to try and request it.

https://developer.apple.com/library/prerelease/ios/samplecode/PrivacyPrompts/Introduction/Intro.html#//apple_ref/doc/uid/DTS40013410-Intro-DontLinkElementID_2
